mayhem integration
mayhemheroes/rust-ini pull request #1
Opened 2022-05-26 01:46 UTC by evanrichter

2022-07-23 23:49 UTC, xansec requested changes
Please make the requested changes.

2022-07-23 23:49 UTC, xansec commented on fuzz/fuzz_targets/fuzz_target_1.rs
> +#![no_main]
If this is the same as `load_from_str`, can we omit this file?

2022-07-24 03:42 UTC, evanrichter commented on fuzz/fuzz_targets/fuzz_target_1.rs
> +#![no_main]
sorry! this was committed by mistake. fixed now

2022-07-25 19:00 UTC, xansec approved these changes
LGTM!

2022-07-25 19:00 UTC, merged